version: 2
updates:
  - package-ecosystem: nuget
    directory: "/src/Supercell.Laser.Server"
    schedule:
      interval: weekly
      day: monday
      time: "13:00"
    open-pull-requests-limit: 10

  - package-ecosystem: nuget
    directory: "/src/Supercell.Laser.Logic"
    schedule:
      interval: weekly
      day: monday
      time: "13:00"
    open-pull-requests-limit: 10

  - package-ecosystem: nuget
    directory: "/src/Supercell.Laser.Titan"
    schedule:
      interval: weekly
      day: monday
      time: "13:00"
    open-pull-requests-limit: 10